// All reusable variables here
#let myLang = "it"
#let myName = "Samuele Corradin"
#let myMatricola = "2068235"
#let myTitle = "Generazione automatica di attributi testuali per contenuti digitali"
#let myDegree = "Tesi di laurea"
#let myUni = "Università degli studi di Padova"
#let myDepartment = "Dipartimento di Matematica ''Tullio Levi-Civita''"
#let myFaculty = "Corso di Laurea in Informatica"
#let profTitle = "Prof. "
#let myProf = "Davide Bresolin"
#let myCompany = "Thron S.p.A."
#let myTutor = "Andrea Didonè"
#let myLocation = "Padova"
#let myAA = "2024-2025"
#let myTime = "Luglio 2025"